const trainerNames = [
  'Ace Trainer Ethan',
  'Ace Trainer Kris',
  'Aroma Lady Dawn',
  'Aroma Lady Gloria',
  'Backpacker Nate',
  'Backpacker Rosa',
  'Black Belt Bede',
  'Black Belt Bruno',
  'Bug Catcher Barry',
  'Bug Catcher Trevor',
  'Camper Brendan',
  'Camper Lucas',
  'Channeler Sabrina',
  'Cool Trainer Leon',
  'Cool Trainer Cynthia',
  'Dragon Tamer Lance',
  'Dragon Tamer Iris',
  'Fisherman Archie',
  'Fisherman Marlon',
  'Gentleman Steven',
  'Gentleman Alder',
  'Hiker Grant',
  'Hiker Milo',
  'Madame Opal',
  'Mystical Psychic Olympia',
  'Ninja Boy Koga',
  'Parasol Lady Fantina',
  'Roughneck Guzma',
  'Ruin Maniac Cyrus',
  'School Kid Bianca',
  'School Kid Shauna',
  'Scientist Colress',
  'Swimmer Misty',
  'Swimmer Wallace',
  'Tamer Giovanni',
  'Tuber Nessa',
  'Veteran Raihan',
  'Veteran Peony',
];

module.exports = trainerNames;
